// HAUSHALTSWAREN

const data = {
  items: [
    {
      id: 1,
      title: "Topf",
      description: "Edelstahltopf mit Deckel",
      price: 19.99,
      image: "../images/haushaltswaren/topf.jpg",
      category: "Haushaltswaren",
    },

    {
      id: 2,
      title: "Kaffemühle",
      description: "zum mahlen von Kaffeebohnen",
      price: 29.99,
      image: "../images/haushaltswaren/kaffemühle.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 3,
      title: "Messerblock",
      description: "Damaszener Stahl Messerblock mit 5 Messern",
      price: 3347.99,
      image: "../images/haushaltswaren/messer.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 4,
      title: "Tupperware",
      description: "Gesundes Plastik",
      price: 9.99,
      image: "../images/haushaltswaren/tupperware.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 5,
      title: "Gewürzregal",
      description: "Gewürzregal Muschel Gold",
      price: 79.99,
      image: "../images/haushaltswaren/gewürzregal.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 6,
      title: "Küchen Set Mix",
      description: "Freude am Kochen ",
      price: 39.99,
      image: "../images/haushaltswaren/mix.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 7,
      title: "Pfannen Set",
      description: "3er Pfannen Set  Durchmesser 18cm, 22cm, 26cm",
      price: 29.99,
      image: "../images/haushaltswaren/pfannen1.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 8,
      title: "Schälmesser",
      description: "5er Set Schälmesser verschiedene Farben",
      price: 6.99,
      image: "../images/haushaltswaren/messer4.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 9,
      title: "Flaschen",
      description: "Flaschen mit Verschluss und Trichter",
      price: 19.99,
      image: "../images/haushaltswaren/flaschen.jpg",
      category: "Haushaltswaren",
    },

    {
      id: 10,
      title: "Kaffemühle",
      description: "zum mahlen von Kaffeebohnen",
      price: 25.99,
      image: "../images/haushaltswaren/kaffemühle2.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 11,
      title: "Messerset",
      description: "Küchen Messer in 6 Formen",
      price: 79.99,
      image: "../images/haushaltswaren/messer2.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 12,
      title: "Töpfe Lila",
      description: "Töpfe in Lila",
      price: 99.99,
      image: "../images/haushaltswaren/töpfelila.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 13,
      title: "Sieb",
      description: "Sieb in drei Größen",
      price: 9.99,
      image: "../images/haushaltswaren/sieb.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 14,
      title: "Töpfe rot",
      description: "Töpfe in rot ",
      price: 89.99,
      image: "../images/haushaltswaren/töpferot.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 15,
      title: "Töpfe und Pfannen",
      description: "7 Töpfe und 2 Pfannen",
      price: 139.99,
      image: "../images/haushaltswaren/töpfe3.jpg",
      category: "Haushaltswaren",
    },
    // ELEKTRONIK
    {
      id: 101,
      title: "Digicam",
      description: "Nikon Digicam mit 20 Megapixeln",
      price: 675,
      image: "../images/elektro/digicamNikon.jpg",
      category: "Elektro",
    },
    {
      id: 102,
      title: "Samsung Galaxy Z Flip 3",
      description: "5G, 128 GB, Black, Dual SIM",
      price: 599.95,
      image: "../images/elektro/samsungHandy.jpg",
      category: "Elektro",
    },
    {
      id: 103,
      title: "Apple 2023 MacBook Pro",
      description:
        "M2 Pro Chip: 16,2 Liquid Retina Display, 16 GB RAM, 512 GB SSD",
      price: 2547.95,
      image: "../images/elektro/macbook.jpg",
      category: "Elektro",
    },
    {
      id: 104,
      title: "Waschmaschine",
      description: "Samsung Waschmaschine mit 8kg Fassungsvermögen",
      price: 999,
      image: "../images/elektro/waschmaschiene2.jpg",
      category: "Elektro",
    },
    {
      id: 105,
      title: "Sony BRAVIA KD-55X75WL LED 4K HDR 55 Zoll",
      description: "Google TV ECO Pack ",
      price: 769,
      image: "../images/elektro/sonyTV.jpg",
      category: "Elektro",
    },
    {
      id: 106,
      title: "CRUA Gaming Monitor 27 Inch FHD 165Hz 1ms, 144HZ/165HZ",
      description:
        "Computer Monitor, Supports Free Sync, 100% sRGB, HDMI, Black",
      price: 149,
      image: "../images/elektro/monitor.jpg",
      category: "Elektro",
    },
    {
      id: 107,
      title: "Sony Playstation 5 Digital Konsole",
      description: "Mit 1 Kontroller",
      price: 499.99,
      image: "../images/elektro/ps5.jpg",
      category: "Elektro",
    },
    {
      id: 108,
      title: "Combusters USB Design Speaker Box PC Tower",
      description: "Black Red Speaker System 2.0 External Audio via USB",
      price: 39,
      image: "../images/elektro/lautsprecher.jpg",
      category: "Elektro",
    },
    {
      id: 109,
      title: "Digicam Blau",
      description: "Rollei Digicam mit 10 Megapixeln",
      price: 75.99,
      image: "../images/elektro/digicamblau.jpg",
      category: "Elektro",
    },
    {
      id: 110,
      title: "Samsung Galaxy ",
      description: "8G, 64 GB, green, Dual SIM",
      price: 599.95,
      image: "../images/elektro/handy3.jpg",
      category: "Elektro",
    },
    {
      id: 111,
      title: "Apple MacBook Air",
      description:
        "M2 Pro Chip: 16,2 Liquid Retina Display, 16 GB RAM, 512 GB SSD",
      price: 999.95,
      image: "../images/elektro/laptop1.jpg",
      category: "Elektro",
    },
    {
      id: 112,
      title: "Waschmaschine",
      description: "Samsung Waschmaschine mit 8kg Fassungsvermögen",
      price: 999,
      image: "../images/elektro/Waschmaschiene6.jpg",
      category: "Elektro",
    },
    {
      id: 113,
      title: "Sony  LED 4K HDR 27 Zoll",
      description: "Sony Gaming Monitor ",
      price: 299.99,
      image: "../images/elektro/monitor.jpg",
      category: "Elektro",
    },
    {
      id: 114,
      title: "Digicam Sony",
      description:
        "Digicam mit 22 Megapixeln, 4K Video, 30x optischer Zoom, 7,5 cm (3 Zoll) LCD Display, NFC, WiFi",
      price: 349,
      image: "../images/elektro/digicamSony.jpg",
      category: "Elektro",
    },
    {
      id: 115,
      title: "Sony Playstation 6 Digital Konsole",
      description: "Mit 1 Kontroller",
      price: 999.99,
      image: "../images/elektro/ps5.jpg",
      category: "Elektro",
    },
    // GARTENZUBEHÖR
    {
      id: 201,
      title: "Rasen",
      description: "Samen für einen schönen Rasen",
      price: 8,
      image: "../images/garten/samen3.jpg",
      category: "Garten",
    },
    {
      id: 202,
      title: "Deko",
      description: "Deko für den Garten",
      price: 15,
      image: "../images/garten/deko.jpg",
      category: "Garten",
    },
    {
      id: 203,
      title: "Werkzeug",
      description: "Werkzeug für den Garten",
      image: "../images/garten/werkzeug3.jpg",
      price: 50,
      category: "Garten",
    },
    {
      id: 204,
      title: "Gießkanne Kombi",
      description: "Gießkanne Mutter & Kind",
      image: "../images/garten/gartenkanne1.jpg",
      price: 4.99,
      category: "Garten",
    },
    {
      id: 205,
      title: "Gemüse Samen",
      description: "14 Sorten Gemüse Vielfalt",
      image: "../images/garten/samen1.jpg",
      price: 9.99,
      category: "Garten",
    },
    {
      id: 206,
      title: "Werkzeug Tasche",
      description: "Werkzeug Tasche für Gärtner",
      image: "../images/garten/werkzeugTasche.jpg",
      price: 9.99,
      category: "Garten",
    },
    {
      id: 207,
      title: "Kunstrasen Set",
      description: "Baby-Safe Kunstrasen + Zubehör aus festen Schaumstoff",
      image: "../images/garten/kunstrasen.jpg",
      price: 29.99,
      category: "Garten",
    },
    {
      id: 208,
      title: "Blumen Samen",
      description: "Blumen Samen für den Garten",
      image: "../images/garten/samen2.jpg",
      price: 12.99,
      category: "Garten",
    },
    {
      id: 209,
      title: "Samen grün",
      description: "Samen für einen schönen Rasen",
      price: 8,
      image: "../images/garten/samen4.jpg",
      category: "Garten",
    },
    {
      id: 210,
      title: "Rechen",
      description: "Rechen für den Garten",
      price: 15,
      image: "../images/garten/rechen.jpg",
      category: "Garten",
    },
    {
      id: 211,
      title: "Werkzeug",
      description: "Werkzeug für den Garten",
      image: "../images/garten/werkzeug1.jpg",
      price: 50,
      category: "Garten",
    },
    {
      id: 212,
      title: "Werkzeug Kombi",
      description: "Schaufel & Harke",
      image: "../images/garten/werkzeug5.jpg",
      price: 4.99,
      category: "Garten",
    },
    {
      id: 213,
      title: "Gemüse Samen",
      description: "14 Sorten Gemüse Vielfalt",
      image: "../images/garten/samen5.jpg",
      price: 9.99,
      category: "Garten",
    },
    {
      id: 214,
      title: "Werkzeug Tasche",
      description: "Werkzeug Tasche für Gärtner",
      image: "../images/garten/werkzeug4.jpg",
      price: 9.99,
      category: "Garten",
    },
    {
      id: 215,
      title: "Kunstrasen Set",
      description: "Baby-Safe Kunstrasen + Zubehör aus festen Schaumstoff",
      image: "../images/garten/kunstrasen.jpg",
      price: 29.99,
      category: "Garten",
    },

    // SCHUHE
    {
      id: 301,
      title: "adidas Herren Strutter Laufschuh",
      description: "Größe 43 Color White",
      image: "../images/schuhe/adidasSchuh.jpg",
      price: 59.99,
      category: "Schuhe",
    },
    {
      id: 302,
      title: "Pimpanockel",
      description: "Pimpanockel Schuhe Größe 37",
      image: "../images/schuhe/hoch.jpg",
      price: 39.99,
      category: "Schuhe",
    },
    {
      id: 303,
      title: "Trackingschuhe",
      description: "Tracking Schuhe Größe 44",
      image: "../images/schuhe/tracking.jpg",
      price: 25.99,
      category: "Schuhe",
    },
    {
      id: 304,
      title: "Rollschuh Kombi",
      description: "Tracking Schuhe Größe 40",
      image: "../images/schuhe/roller.jpg",
      price: 49.99,
      category: "Schuhe",
    },
    {
      id: 305,
      title: "sOliver",
      description: "sOliver Sommer",
      image: "../images/schuhe/sOliver.jpg",
      price: 19.99,
      category: "Schuhe",
    },
    {
      id: 306,
      title: "Nike Air Max ",
      description: "Axis Premium Men's Athletics Shoes Grösse 42",
      image: "../images/schuhe/nikeblack.jpg",
      price: 49.99,
      category: "Schuhe",
    },
    {
      id: 307,
      title: "Dockers by Gerli",
      description: "Women's Lace-Up Boots Größe 40",
      image: "../images/schuhe/dockers.jpg",
      price: 50.99,
      category: "Schuhe",
    },
    {
      id: 308,
      title: "Onsoyours Sexy High Heels",
      description: "Women Summer Sandals Open Toe and Zip Grösse 39",
      image: "../images/schuhe/highHeels.jpg",
      price: 54,
      category: "Schuhe",
    },
    {
      id: 309,
      title: "adidas Herren Strutter Laufschuh",
      description: "Größe 43 Color White",
      image: "../images/schuhe/adidasSchuh.jpg",
      price: 59.99,
      category: "Schuhe",
    },
    {
      id: 310,
      title: "Pimpanockel",
      description: "Pimpanockel Schuhe Größe 37",
      image: "../images/schuhe/hoch.jpg",
      price: 39.99,
      category: "Schuhe",
    },
    {
      id: 311,
      title: "Trackingschuhe",
      description: "Tracking Schuhe Größe 44",
      image: "../images/schuhe/tracking.jpg",
      price: 25.99,
      category: "Schuhe",
    },
    {
      id: 312,
      title: "Rollschuh Kombi",
      description: "Tracking Schuhe Größe 40",
      image: "../images/schuhe/roller.jpg",
      price: 49.99,
      category: "Schuhe",
    },
    {
      id: 313,
      title: "sOliver",
      description: "sOliver Sommer",
      image: "../images/schuhe/sOliver.jpg",
      price: 19.99,
      category: "Schuhe",
    },
    {
      id: 314,
      title: "Nike Air Max ",
      description: "Axis Premium Men's Athletics Shoes Grösse 42",
      image: "../images/schuhe/nikeblack.jpg",
      price: 49.99,
      category: "Schuhe",
    },
    {
      id: 315,
      title: "Dockers by Gerli",
      description: "Women's Lace-Up Boots Größe 40",
      image: "../images/schuhe/dockers.jpg",
      price: 50.99,
      category: "Schuhe",
    },
    // SCHMUCK
    {
      id: 401,
      title: "Miore Women's Gold Chain",
      description:
        "ith Gemstone in Teardrop Shape - Filigree Necklace in 9ct Yellow Gold / White Gold (375)",
      image: "../images/schmuck/ketteRoterStein.jpg",
      price: 128,
      category: "Schmuck",
    },
    {
      id: 402,
      title: "Miore Gold and Silver Hoop Earrings",
      description:
        "925 Sterling Silver with Zirconia Stones, Jewellery Box for Gift (4.5 x 16 mm) ",
      image: "../images/schmuck/mioreOhrringe.jpg",
      price: 39,
      category: "Schmuck",
    },
    {
      id: 403,
      title: "Eternal Real Rose with Heart Necklace and Earrings",
      description: "925 Sterling Silver, Infinity Roses, Jewellery Gift Box",
      image: "../images/schmuck/roseSet.jpg",
      price: 29.99,
      category: "Schmuck",
    },
    {
      id: 404,
      title: "LIEBESKIND",
      description: "Damen-Handketten Edelstahl LJ-0344-B-20",
      image: "../images/schmuck/armreif1.jpg",
      price: 128,
      category: "Schmuck",
    },
    {
      id: 405,
      title: "CDE Schmuckset Damen",
      description:
        "Halskette Kette Ohrringe Set, Rosegold Schmuck Set mit Geschenkbox",
      image: "../images/schmuck/heartRainbow.jpg",
      price: 39.99,
      category: "Schmuck",
    },
    {
      id: 406,
      title: "Tommy Hilfiger",
      description: "Women’s Stainless Steel Necklace",
      image: "../images/schmuck/tommyHilfiger.jpg",
      price: 28.99,
      category: "Schmuck",
    },
    {
      id: 407,
      title: "Bering Women",
      description: "Analogue Quartz Watch, Stainless Steel",
      image: "../images/schmuck/uhrGold.jpg",
      price: 102.99,
      category: "Schmuck",
    },
    {
      id: 408,
      title: "BOSS Jewelry Medallion",
      description: "Women's Hoop Earrings, Stainless Steel",
      image: "../images/schmuck/hugoBoss.jpg",
      price: 34.99,
      category: "Schmuck",
    },
    {
      id: 409,
      title: "Miore Women's Gold Chain",
      description:
        "ith Gemstone in Teardrop Shape - Filigree Necklace in 9ct Yellow Gold / White Gold (375)",
      image: "../images/schmuck/ketteRoterStein.jpg",
      price: 128,
      category: "Schmuck",
    },
    {
      id: 410,
      title: "Miore Gold and Silver Hoop Earrings",
      description:
        "925 Sterling Silver with Zirconia Stones, Jewellery Box for Gift (4.5 x 16 mm) ",
      image: "../images/schmuck/mioreOhrringe.jpg",
      price: 39,
      category: "Schmuck",
    },
    {
      id: 411,
      title: "Eternal Real Rose with Heart Necklace and Earrings",
      description: "925 Sterling Silver, Infinity Roses, Jewellery Gift Box",
      image: "../images/schmuck/roseSet.jpg",
      price: 29.99,
      category: "Schmuck",
    },
    {
      id: 412,
      title: "LIEBESKIND",
      description: "Damen-Handketten Edelstahl LJ-0344-B-20",
      image: "../images/schmuck/armreif1.jpg",
      price: 128,
      category: "Schmuck",
    },
    {
      id: 413,
      title: "CDE Schmuckset Damen",
      description:
        "Halskette Kette Ohrringe Set, Rosegold Schmuck Set mit Geschenkbox",
      image: "../images/schmuck/heartRainbow.jpg",
      price: 39.99,
      category: "Schmuck",
    },
    {
      id: 414,
      title: "Tommy Hilfiger",
      description: "Women’s Stainless Steel Necklace",
      image: "../images/schmuck/tommyHilfiger.jpg",
      price: 28.99,
      category: "Schmuck",
    },
    {
      id: 415,
      title: "Bering Women",
      description: "Analogue Quartz Watch, Stainless Steel",
      image: "../images/schmuck/uhrGold.jpg",
      price: 102.99,
      category: "Schmuck",
    },
    // Outdoor
    {
      id: 501,
      title: "Kesser® Camping Kitchen Unit",
      description:
        "Including Carry Bag, Camping Cupboard with Aluminium Frame, Travel Kitchen, Tent Cupboard",
      image: "../images/outdoor/kitchen.jpg",
      price: 74.99,
      category: "Outdoor",
    },
    {
      id: 502,
      title: "Dry Shift Wasserfilter Outdoor",
      description:
        "3000L Kapazität mit Trinkblase 3L [𝐊𝐫𝐢𝐬𝐞𝐧𝐬𝐢𝐜𝐡𝐞𝐫] entfernt 99,99% aller Keime und Bakterien",
      image: "../images/outdoor/wasserfilter.jpg",
      price: 54.99,
      category: "Outdoor",
    },
    {
      id: 503,
      title: "zeitgeist OUTDOOR Schlafsack Erwachsene",
      description:
        "Wasserabweisender Mumienschlafsack Leicht 10°C Komfort Sommer ",
      image: "../images/outdoor/schlafsack.jpg",
      price: 59.99,
      category: "Outdoor",
    },
    {
      id: 504,
      title: "Tavaler Camping Lantern",
      description: "8000 mAh Battery USB C Rechargeable Camping Lamp with LED",
      image: "../images/outdoor/laterne.jpg",
      price: 26.99,
      category: "Outdoor",
    },
    {
      id: 505,
      title: "OTraki Hammock with Mosquito Net",
      description:
        "Tent Tarpaulin Travel Camping Hammock Outdoor Hammock 200 kg",
      image: "../images/outdoor/haengematte.jpg",
      price: 39.99,
      category: "Outdoor",
    },
    {
      id: 506,
      title: "Pop Up Festival Tent",
      description: "for 2 or 3 People - 220/240 cm ",
      image: "../images/outdoor/wurfzelt.jpg",
      price: 34.99,
      category: "Outdoor",
    },
    {
      id: 507,
      title: "Bushcraft 101 - Überleben in der Wildnis ",
      description:
        "Der ultimative Survival Praxisführer: Überlebenstechniken, Extremsituationen, Outdoor",
      image: "../images/outdoor/buch.jpg",
      price: 9.99,
      category: "Outdoor",
    },
    {
      id: 508,
      title: " Camping Accessories, Multifunctional Gadgets",
      description:
        "17-in-1 Fire Starter Sticks, Saw Screwdriver, Bottle Opener, Whistle and More",
      image: "../images/outdoor/survivalMesser.jpg",
      price: 24.99,
      category: "Outdoor",
    },
    {
      id: 509,
      title: "Kesser® Camping Kitchen Unit",
      description:
        "Including Carry Bag, Camping Cupboard with Aluminium Frame, Travel Kitchen, Tent Cupboard",
      image: "../images/outdoor/kitchen.jpg",
      price: 74.99,
      category: "Outdoor",
    },
    {
      id: 510,
      title: "Dry Shift Wasserfilter Outdoor",
      description:
        "3000L Kapazität mit Trinkblase 3L [𝐊𝐫𝐢𝐬𝐞𝐧𝐬𝐢𝐜𝐡𝐞𝐫] entfernt 99,99% aller Keime und Bakterien",
      image: "../images/outdoor/wasserfilter.jpg",
      price: 54.99,
      category: "Outdoor",
    },
    {
      id: 511,
      title: "zeitgeist OUTDOOR Schlafsack Erwachsene",
      description:
        "Wasserabweisender Mumienschlafsack Leicht 10°C Komfort Sommer ",
      image: "../images/outdoor/schlafsack.jpg",
      price: 59.99,
      category: "Outdoor",
    },
    {
      id: 512,
      title: "Tavaler Camping Lantern",
      description: "8000 mAh Battery USB C Rechargeable Camping Lamp with LED",
      image: "../images/outdoor/laterne.jpg",
      price: 26.99,
      category: "Outdoor",
    },
    {
      id: 513,
      title: "OTraki Hammock with Mosquito Net",
      description:
        "Tent Tarpaulin Travel Camping Hammock Outdoor Hammock 200 kg",
      image: "../images/outdoor/haengematte.jpg",
      price: 39.99,
      category: "Outdoor",
    },
    {
      id: 514,
      title: "Pop Up Festival Tent",
      description: "for 2 or 3 People - 220/240 cm ",
      image: "../images/outdoor/wurfzelt.jpg",
      price: 34.99,
      category: "Outdoor",
    },
    {
      id: 515,
      title: "Bushcraft 101 - Überleben in der Wildnis ",
      description:
        "Der ultimative Survival Praxisführer: Überlebenstechniken, Extremsituationen, Outdoor",
      image: "../images/outdoor/buch.jpg",
      price: 9.99,
      category: "Outdoor",
    },
    // MODE
    {
      id: 601,
      title: "TRUTH & FABLE Women's Bodycon",
      description: "Midi Dress",
      image: "../images/mode/kleidPunkte.jpg",
      price: 59.99,
      category: "Mode",
    },
    {
      id: 602,
      title: "Amazon Brand - TRUTH & FABLE",
      description: "Women's Short Sleeve Bandeau Jumpsuit",
      image: "../images/mode/hoseKombiRot.jpg",
      price: 69.99,
      category: "Mode",
    },
    {
      id: 603,
      title: "Wneedu Women's Cap Sleeve T-Shirt",
      description: "Summer Tank Top, Simple, Casual, Loose Fit Blouses",
      image: "../images/mode/womanTshirt.jpg",
      price: 19.99,
      category: "Mode",
    },
    {
      id: 604,
      title: "ONLY Women's Onlibiza Life Short",
      description: "Skirt WVN Noos Skirt",
      image: "../images/mode/rockGruen.jpg",
      price: 24.99,
      category: "Mode",
    },
    {
      id: 605,
      title: "DIXXSON Premium Men's Boxer Shorts",
      description:
        "Pack of 3, Breathable Underwear for Men with Optimal Fit and Soft Cotton (Size M - 3XL)",
      image: "../images/mode/boxer.jpg",
      price: 29.95,
      category: "Mode",
    },
    {
      id: 606,
      title: "Yazubi Kyle Men's Chino Trousers",
      description: "Slim Fit, Casual with Stretch",
      image: "../images/mode/hoseStretch.jpg",
      price: 39.95,
      category: "Mode",
    },
    {
      id: 607,
      title: "Meilicloth Denim Shirt",
      description: "Men's Business Casual Long Sleeve Shirt",
      image: "../images/mode/hemd.jpg",
      price: 24.95,
      category: "Mode",
    },
    {
      id: 608,
      title: "Steffen Klein Men's Suit",
      description: "Regular Fit, Elastic",
      image: "../images/mode/anzug.jpg",
      price: 159.99,
      category: "Mode",
    },
    {
      id: 609,
      title: "TRUTH & FABLE Women's Bodycon",
      description: "Midi Dress",
      image: "../images/mode/kleidPunkte.jpg",
      price: 59.99,
      category: "Mode",
    },
    {
      id: 610,
      title: "Amazon Brand - TRUTH & FABLE",
      description: "Women's Short Sleeve Bandeau Jumpsuit",
      image: "../images/mode/hoseKombiRot.jpg",
      price: 69.99,
      category: "Mode",
    },
    {
      id: 611,
      title: "Wneedu Women's Cap Sleeve T-Shirt",
      description: "Summer Tank Top, Simple, Casual, Loose Fit Blouses",
      image: "../images/mode/womanTshirt.jpg",
      price: 19.99,
      category: "Mode",
    },
    {
      id: 612,
      title: "ONLY Women's Onlibiza Life Short",
      description: "Skirt WVN Noos Skirt",
      image: "../images/mode/rockGruen.jpg",
      price: 24.99,
      category: "Mode",
    },
    {
      id: 613,
      title: "DIXXSON Premium Men's Boxer Shorts",
      description:
        "Pack of 3, Breathable Underwear for Men with Optimal Fit and Soft Cotton (Size M - 3XL)",
      image: "../images/mode/boxer.jpg",
      price: 29.95,
      category: "Mode",
    },
    {
      id: 614,
      title: "Yazubi Kyle Men's Chino Trousers",
      description: "Slim Fit, Casual with Stretch",
      image: "../images/mode/hoseStretch.jpg",
      price: 39.95,
      category: "Mode",
    },
    {
      id: 615,
      title: "Meilicloth Denim Shirt",
      description: "Men's Business Casual Long Sleeve Shirt",
      image: "../images/mode/hemd.jpg",
      price: 24.95,
      category: "Mode",
    },
    // KINDERMODE
    {
      id: 701,
      title: "SJACK & JONES Boy",
      description: "padded jacket boys' hood",
      image: "../images/kindermode/j&jJacke.jpg",
      price: 65.95,
      category: "Kindermode",
    },
    {
      id: 702,
      title: "C&A Children's Boys' Hooded Sweat",
      description: "Jacket Colour-Blocking Cotton",
      image: "../images/kindermode/roteJacke.jpg",
      price: 9.99,
      category: "Kindermode",
    },
    {
      id: 703,
      title: "FYMNSI Mädchen Vintage 1950er",
      description: "Rockabilly Partykleider Faltenrock Knielang für 4-12 Jahre",
      image: "../images/kindermode/kleidBlack.jpg",
      price: 25.95,
      category: "Kindermode",
    },
    {
      id: 704,
      title: "LOLANTA 4 Pieces Toddler Boys",
      description: "Summer Boys Suit",
      image: "../images/kindermode/shortKombi.jpg",
      price: 39.99,
      category: "Kindermode",
    },
    {
      id: 705,
      title: "10 pairs of children's cotton socks",
      description: "boys & girls",
      image: "../images/kindermode/socks.jpg",
      price: 15.99,
      category: "Kindermode",
    },
    {
      id: 706,
      title: "NAME IT Baby-Boys Pyjamas",
      description: "100% Cotton",
      image: "../images/kindermode/pyjamas.jpg",
      price: 19.99,
      category: "Kindermode",
    },
    {
      id: 707,
      title: "JACK & JONES",
      description: "ungen Kapuzenpullover",
      image: "../images/kindermode/j&jHoody.jpg",
      price: 17.99,
      category: "Kindermode",
    },
    {
      id: 708,
      title: "CAMLAKEE Children's dinosaur hoodies",
      description: "boys' 3D print hoodie, girls' jumper",
      image: "../images/kindermode/dinoHoody.jpg",
      price: 29.95,
      category: "Kindermode",
    },
    {
      id: 709,
      title: "SJACK & JONES Boy",
      description: "padded jacket boys' hood",
      image: "../images/kindermode/j&jJacke.jpg",
      price: 65.95,
      category: "Kindermode",
    },
    {
      id: 710,
      title: "C&A Children's Boys' Hooded Sweat",
      description: "Jacket Colour-Blocking Cotton",
      image: "../images/kindermode/roteJacke.jpg",
      price: 9.99,
      category: "Kindermode",
    },
    {
      id: 711,
      title: "FYMNSI Mädchen Vintage 1950er",
      description: "Rockabilly Partykleider Faltenrock Knielang für 4-12 Jahre",
      image: "../images/kindermode/kleidBlack.jpg",
      price: 25.95,
      category: "Kindermode",
    },
    {
      id: 712,
      title: "LOLANTA 4 Pieces Toddler Boys",
      description: "Summer Boys Suit",
      image: "../images/kindermode/shortKombi.jpg",
      price: 39.99,
      category: "Kindermode",
    },
    {
      id: 713,
      title: "10 pairs of children's cotton socks",
      description: "boys & girls",
      image: "../images/kindermode/socks.jpg",
      price: 15.99,
      category: "Kindermode",
    },
    {
      id: 714,
      title: "NAME IT Baby-Boys Pyjamas",
      description: "100% Cotton",
      image: "../images/kindermode/pyjamas.jpg",
      price: 19.99,
      category: "Kindermode",
    },
    {
      id: 715,
      title: "JACK & JONES",
      description: "ungen Kapuzenpullover",
      image: "../images/kindermode/j&jHoody.jpg",
      price: 17.99,
      category: "Kindermode",
    },
  ],
  // categorys: [
  //   {
  //     id: 1,
  //     title: "Haushalt",
  //     image: "images/imagesCard/scott-umstattd-wxruheY5nG8-unsplash.jpg",
  //     category: "Haushaltswaren",
  //   },
  //   {
  //     id: 2,
  //     title: "Elektro",
  //     image: "images/imagesCard/Elektro.jpg",
  //     category: "Elektro",
  //   },
  //   {
  //     id: 3,
  //     title: "Garten",
  //     image: "images/imagesCard/daniel-watson-8vBpYpTGo90-unsplash.jpg",
  //     category: "Garten",
  //   },
  //   {
  //     id: 4,
  //     title: "Mode",
  //     image: "images/imagesCard/CardMode.jpg",
  //     category: "Mode",
  //   },
  //   {
  //     id: 4,
  //     title: "Mode",
  //     image: "images/imagesCard/CardMode.jpg",
  //     category: "Mode",
  //   },
  // ],
};

export default data;
